export const futureContractsJson = ref([
  {
    name: "Micro E-mini S&P 500",
    symbol: "MES",
    type: "Micro E-mini Futures",
    exchange: "CME",
    unit: "USD",
    contractSize: 5,
    contractSizeExpl: "$5 x S&P Index",
    months: "H,M,U,Z",
    tick: 0.25,
    value: 1.25,
  },
  {
    name: "Micro E-mini Nasdaq-100",
    symbol: "MNQ",
    type: "Micro E-mini Futures",
    exchange: "CME",
    unit: "USD",
    contractSize: 2,
    contractSizeExpl: "$2 x Nasdaq-100 Index",
    months: "H,M,U,Z",
    tick: 0.25,
    value: 0.5,
  },
  {
    name: "Micro E-mini Dow",
    symbol: "MYM",
    type: "Micro E-mini Futures",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 0,
    contractSizeExpl: "$0.50 x DJIA Index",
    months: "H,M,U,Z",
    tick: 1,
    value: 0,
  },
  {
    name: "Micro E-mini Russell 2000",
    symbol: "M2K",
    type: "Micro E-mini Futures",
    exchange: "CME",
    unit: "USD",
    contractSize: 5,
    contractSizeExpl: "$5 x Russell 2000 Index",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 0.5,
  },
  {
    name: "Micro-DAX",
    symbol: "FDXS",
    type: "Micro E-mini Futures",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 1,
    contractSizeExpl: "€1 x Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 1,
  },
  {
    name: "Micro-EURO STOXX 50",
    symbol: "FSXE",
    type: "Micro E-mini Futures",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 1,
    contractSizeExpl: "€1 x Index Value",
    months: "H,M,U,Z",
    tick: 0.5,
    value: 0.5,
  },
  {
    name: "E-mini S&P 500",
    symbol: "ES",
    type: "Stock Index",
    exchange: "CME",
    unit: "USD",
    contractSize: 50,
    contractSizeExpl: "$50 x Index Value",
    months: "H,M,U,Z",
    tick: 0.25,
    value: 12.5,
  },
  {
    name: "E-mini Nasdaq-100",
    symbol: "NQ",
    type: "Stock Index",
    exchange: "CME",
    unit: "USD",
    contractSize: 20,
    contractSizeExpl: "$20 x Index Value",
    months: "H,M,U,Z",
    tick: 0.25,
    value: 5,
  },
  {
    name: "E-mini Dow ($5)",
    symbol: "YM",
    type: "Stock Index",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 5,
    contractSizeExpl: "$5 x Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 5,
  },
  {
    name: "E-mini Russell 2000",
    symbol: "RTY",
    type: "Stock Index",
    exchange: "CME",
    unit: "USD",
    contractSize: 50,
    contractSizeExpl: "$50 x Index Value",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 5,
  },
  {
    name: "E-mini S&P MidCap 400",
    symbol: "EMD",
    type: "Stock Index",
    exchange: "CME",
    unit: "USD",
    contractSize: 100,
    contractSizeExpl: "$100 x Index Value",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 10,
  },
  {
    name: "NIKKEI 225\/USD",
    symbol: "NKD",
    type: "Stock Index",
    exchange: "CME",
    unit: "USD",
    contractSize: 5,
    contractSizeExpl: "$5 x Index Value",
    months: "H,M,U,Z",
    tick: 5,
    value: 25,
  },
  {
    name: "DAX",
    symbol: "FDAX",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 25,
    contractSizeExpl: "€25 x Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 25,
  },
  {
    name: "Mini-DAX",
    symbol: "FDXM",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 5,
    contractSizeExpl: "€5 x Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 5,
  },
  {
    name: "EURO STOXX 50",
    symbol: "FESX",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 20,
    contractSizeExpl: "€10 x Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 20,
  },
  {
    name: "STOXX Europe 600",
    symbol: "FXXP",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 50,
    contractSizeExpl: "€50 x Index Value",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 5,
  },
  {
    name: "EURO STOXX Banks",
    symbol: "FESB",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 50,
    contractSizeExpl: "€50 x Index Value",
    months: "H,M,U,Z",
    tick: 0.05,
    value: 2.5,
  },
  {
    name: "VSTOXX",
    symbol: "FVS",
    type: "Stock Index",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100,
    contractSizeExpl: "€100 x Index Value",
    months: "see exch.",
    tick: 0.05,
    value: 5,
  },
  {
    name: "CBOE Volatility Index (VIX)",
    symbol: "VX",
    type: "Stock Index",
    exchange: "CFE\/CBOE",
    unit: "USD",
    contractSize: 1000,
    contractSizeExpl: "$1000 x Index Value",
    months: "see exch.",
    tick: 0.05,
    value: 50,
  },
  {
    name: "Mini CBOE Volatility Index (Mini VIX)",
    symbol: "VXM",
    type: "Stock Index",
    exchange: "CFE\/CBOE",
    unit: "USD",
    contractSize: 100,
    contractSizeExpl: "$100 x Index Value",
    months: "see exch.",
    tick: 0.05,
    value: 5,
  },
  {
    name: "SGX Nifty 50 Index",
    symbol: "IN",
    type: "Stock Index",
    exchange: "Singapore Exchange (SGX)",
    unit: "USD",
    contractSize: 2,
    contractSizeExpl: "$2 x Index Value",
    months: "H,M,U,Z",
    tick: 0.5,
    value: 1,
  },
  {
    name: "SGX USD Nikkei 225 Index",
    symbol: "NU",
    type: "Stock Index",
    exchange: "Singapore Exchange (SGX)",
    unit: "USD",
    contractSize: 5,
    contractSizeExpl: "$5 x Index Value",
    months: "H,M,U,Z",
    tick: 5,
    value: 25,
  },
  {
    name: "FTSE Taiwan Stock Index",
    symbol: "TW",
    type: "Stock Index",
    exchange: "Singapore Exchange (SGX)",
    unit: "USD",
    contractSize: 100,
    contractSizeExpl: "US$100 x SGX MSCI Taiwan Index",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 10,
  },
  {
    name: "ASX SPI200 Index",
    symbol: "AP",
    type: "Stock Index",
    exchange: "Australian Securities Exchange (ASX)",
    unit: "USD",
    contractSize: 25,
    contractSizeExpl: "$25 X Index Value",
    months: "H,M,U,Z",
    tick: 1,
    value: 25,
  },
  {
    name: "British Pound",
    symbol: "6B",
    type: "Currencies",
    exchange: "CME",
    unit: "GBP",
    contractSize: 62500,
    contractSizeExpl: "62.5K £",
    months: "H,M,U,Z",
    tick: 0.0001,
    value: 6.25,
  },
  {
    name: "Canadian Dollar",
    symbol: "6C",
    type: "Currencies",
    exchange: "CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "100K $",
    months: "H,M,U,Z",
    tick: 5e-5,
    value: 5,
  },
  {
    name: "Euro FX",
    symbol: "6E",
    type: "Currencies",
    exchange: "CME",
    unit: "USD",
    contractSize: 125000,
    contractSizeExpl: "125K €",
    months: "H,M,U,Z",
    tick: 5e-5,
    value: 6.25,
  },
  {
    name: "Japanese Yen",
    symbol: "6J",
    type: "Currencies",
    exchange: "CME",
    unit: "USD",
    contractSize: 12500000,
    contractSizeExpl: "12.5 mil ¥",
    months: "H,M,U,Z",
    tick: 5e-7,
    value: 6.25,
  },
  {
    name: "New Zealand Dollar",
    symbol: "6N",
    type: "Currencies",
    exchange: "CME",
    unit: "NZD",
    contractSize: 100000,
    contractSizeExpl: "100K NZD",
    months: "H,M,U,Z",
    tick: 5e-5,
    value: 5,
  },
  {
    name: "Swiss Franc",
    symbol: "6S",
    type: "Currencies",
    exchange: "CME",
    unit: "CHF",
    contractSize: 125000,
    contractSizeExpl: "125K CHF",
    months: "H,M,U,Z",
    tick: 0.0001,
    value: 12.5,
  },
  {
    name: "E-mini Euro FX",
    symbol: "E7",
    type: "Currencies",
    exchange: "CME",
    unit: "EUR",
    contractSize: 62500,
    contractSizeExpl: "62.5K €",
    months: "H,M,U,Z",
    tick: 0.0001,
    value: 6.25,
  },
  {
    name: "E-mini Japanese Yen",
    symbol: "J7",
    type: "Currencies",
    exchange: "CME",
    unit: "YEN",
    contractSize: 62500000,
    contractSizeExpl: "6.25 mil ¥",
    months: "H,M,U,Z",
    tick: 1e-6,
    value: 62.5,
  },
  {
    name: "Micro AUD\/USD",
    symbol: "M6A",
    type: "Currencies",
    exchange: "CME",
    unit: "AUD",
    contractSize: 10000,
    contractSizeExpl: "10K AUD",
    months: "H,M,U,Z",
    tick: 0.0001,
    value: 1,
  },
  {
    name: "Dollar Index",
    symbol: "DX",
    type: "Currencies",
    exchange: "ICE Futures U.S.",
    unit: "USD",
    contractSize: 1000,
    contractSizeExpl: "$1000 X Index Value",
    months: "H,M,U,Z",
    tick: 0.005,
    value: 5,
  },
  {
    name: "Crude Oil",
    symbol: "CL",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "barrels",
    contractSize: 1000,
    contractSizeExpl: "1,000 barrels",
    months: "All",
    tick: 0.01,
    value: 10,
  },
  {
    name: "E-mini Crude Light",
    symbol: "QM",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "barrels",
    contractSize: 500,
    contractSizeExpl: "500 barrels",
    months: "All",
    tick: 0.025,
    value: 12.5,
  },
  {
    name: "Micro WTI Crude Oil",
    symbol: "MCL",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "barrels",
    contractSize: 100,
    contractSizeExpl: "100 barrels",
    months: "All",
    tick: 0.01,
    value: 1,
  },
  {
    name: "Natural Gas",
    symbol: "NG",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "mmBtu",
    contractSize: 10000,
    contractSizeExpl: "10,000 mmBtu",
    months: "All",
    tick: 0.001,
    value: 10,
  },
  {
    name: "E-mini Natural Gas",
    symbol: "QG",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "mmBtu",
    contractSize: 2500,
    contractSizeExpl: "2,500 mmBtu",
    months: "All",
    tick: 0.005,
    value: 12.5,
  },
  {
    name: "RBOB Gasoline",
    symbol: "RB",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "gal",
    contractSize: 42000,
    contractSizeExpl: "42K gal",
    months: "All",
    tick: 0.0001,
    value: 4.2,
  },
  {
    name: "Heating Oil",
    symbol: "HO",
    type: "Energies",
    exchange: "NYMEX\/CME",
    unit: "gal",
    contractSize: 42000,
    contractSizeExpl: "42K gal",
    months: "All",
    tick: 0.0001,
    value: 4.2,
  },
  {
    name: "ICE Brent Crude",
    symbol: "B",
    type: "Energies",
    exchange: "ICE Europe - Commodities",
    unit: "gal",
    contractSize: 42000,
    contractSizeExpl: "42K gal",
    months: "All",
    tick: 0.01,
    value: 420,
  },
  {
    name: "ICE WTI Crude",
    symbol: "T",
    type: "Energies",
    exchange: "ICE Europe - Commodities",
    unit: "gal",
    contractSize: 42000,
    contractSizeExpl: "42K gal",
    months: "All",
    tick: 0.01,
    value: 420,
  },
  {
    name: "ICE Gas Oil",
    symbol: "G",
    type: "Energies",
    exchange: "ICE Europe - Commodities",
    unit: "tonnes",
    contractSize: 100,
    contractSizeExpl: "100 tonnes",
    months: "H,M,U,Z",
    tick: 0.25,
    value: 25,
  },
  {
    name: "Gold",
    symbol: "GC",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 100,
    contractSizeExpl: "100 oz",
    months: "G,J,M,Q,V,Z",
    tick: 0.1,
    value: 10,
  },
  {
    name: "E-mini Gold",
    symbol: "QO",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 50,
    contractSizeExpl: "50 oz",
    months: "F,G,J,M,Q,V,Z",
    tick: 0.25,
    value: 12.5,
  },
  {
    name: "Micro Gold",
    symbol: "MGC",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 10,
    contractSizeExpl: "10 oz",
    months: "G,J,M,Q,V,Z",
    tick: 0.1,
    value: 1,
  },
  {
    name: "Copper",
    symbol: "HG",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "lbs",
    contractSize: 25000,
    contractSizeExpl: "25K lbs",
    months: "All",
    tick: 0.0005,
    value: 12.5,
  },
  {
    name: "E-mini Copper",
    symbol: "QC",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "lbs",
    contractSize: 12500,
    contractSizeExpl: "12,500 lbs",
    months: "All",
    tick: 0.002,
    value: 25,
  },
  {
    name: "Silver",
    symbol: "SI",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 5000,
    contractSizeExpl: "5,000 oz",
    months: "F,H,K,N,U,Z",
    tick: 0.005,
    value: 25,
  },
  {
    name: "E-mini Silver",
    symbol: "QI",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 2500,
    contractSizeExpl: "2,500 oz",
    months: "F,G,H,K,N,U,Z",
    tick: 0.0125,
    value: 31.25,
  },
  {
    name: "E-micro Silver",
    symbol: "SIL",
    type: "Metals",
    exchange: "COMEX\/CME",
    unit: "oz",
    contractSize: 1000,
    contractSizeExpl: "1,000 oz",
    months: "F,H,K,N,U,V,X,Z",
    tick: 0.01,
    value: 10,
  },
  {
    name: "Platinum",
    symbol: "PL",
    type: "Metals",
    exchange: "NYMEX\/CME",
    unit: "oz",
    contractSize: 50,
    contractSizeExpl: "50 oz",
    months: "F,J,N,V",
    tick: 0.1,
    value: 5,
  },
  {
    name: "Mini Gold",
    symbol: "YG",
    type: "Metals",
    exchange: "ICE Futures U.S.",
    unit: "oz",
    contractSize: 33,
    contractSizeExpl: "33.15 oz",
    months: "All",
    tick: 0.1,
    value: 3.3000000000000003,
  },
  {
    name: "Mini-Silver",
    symbol: "YI",
    type: "Metals",
    exchange: "ICE Futures U.S.",
    unit: "oz",
    contractSize: 1000,
    contractSizeExpl: "1,000 oz",
    months: "All",
    tick: 0.001,
    value: 1,
  },
  {
    name: "100 oz Gold",
    symbol: "ZG",
    type: "Metals",
    exchange: "ICE Futures U.S.",
    unit: "oz",
    contractSize: 100,
    contractSizeExpl: "100 oz",
    months: "G,J,M,Q,V,X,Z",
    tick: 0.1,
    value: 10,
  },
  {
    name: "5000 oz Silver",
    symbol: "ZI",
    type: "Metals",
    exchange: "ICE Futures U.S.",
    unit: "oz",
    contractSize: 5000,
    contractSizeExpl: "5,000 oz",
    months: "F,H,K,N,U,V,X,Z",
    tick: 0.001,
    value: 5,
  },
  {
    name: "Ultra U.S. Treasury Bond",
    symbol: "UB",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "$100K bond",
    months: "H,M,U,Z",
    tick: 0.03125,
    value: 3125,
  },
  {
    name: "Ultra 10-Year U.S. Treasury Note",
    symbol: "TN",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "$100K Note",
    months: "H,M,U,Z",
    tick: 0.03125,
    value: 3125,
  },
  {
    name: "3-Year U.S. Treasury Note",
    symbol: "Z3N",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 300000,
    contractSizeExpl: "$300K note",
    months: "H,M,U,Z",
    tick: 0.0078125,
    value: 2343.75,
  },
  {
    name: "U.S. Treasury Bond",
    symbol: "ZB",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "$100K bond",
    months: "H,M,U,Z",
    tick: 0.03125,
    value: 3125,
  },
  {
    name: "Micro 30-Year Yield",
    symbol: "30YY",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 10,
    contractSizeExpl: "$10.00 DV01",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 1,
  },
  {
    name: "5-Year U.S. Treasury Note",
    symbol: "ZF",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "$100K note",
    months: "H,M,U,Z",
    tick: 0.0078125,
    value: 781.25,
  },
  {
    name: "Micro 5-Year Yield",
    symbol: "5YY",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 10,
    contractSizeExpl: "$10.00 DV01",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 1,
  },
  {
    name: "10-Year U.S. Treasury Note",
    symbol: "ZN",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 100000,
    contractSizeExpl: "$100K note",
    months: "H,M,U,Z",
    tick: 0.015625,
    value: 1562.5,
  },
  {
    name: "Micro 10-Year Yield",
    symbol: "10YY",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 10,
    contractSizeExpl: "$10.00 DV01",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 1,
  },
  {
    name: "30-Day Federal Funds",
    symbol: "ZQ",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 5000000,
    contractSizeExpl: "$5 mil",
    months: "All",
    tick: 0.005,
    value: 25000,
  },
  {
    name: "2-Year U.S. Treasury Note",
    symbol: "ZT",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 200000,
    contractSizeExpl: "$200K note",
    months: "H,M,U,Z",
    tick: 0.0078125,
    value: 1562.5,
  },
  {
    name: "Micro 2-Year Yield",
    symbol: "2YY",
    type: "Financials",
    exchange: "CBOT\/CME",
    unit: "USD",
    contractSize: 10,
    contractSizeExpl: "$10.00 DV01",
    months: "H,M,U,Z",
    tick: 0.1,
    value: 1,
  },
  {
    name: "Eurodollar",
    symbol: "GE",
    type: "Financials",
    exchange: "CME",
    unit: "USD",
    contractSize: 1000000,
    contractSizeExpl: "$1 mil",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10000,
  },
  {
    name: "Long-Term Euro-BTP",
    symbol: "FBTP",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K€",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10,
  },
  {
    name: "Short-Term Euro-BTP",
    symbol: "FBTS",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K€",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10,
  },
  {
    name: "Euro-Bund",
    symbol: "FGBL",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K €",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10,
  },
  {
    name: "Euro-Bobl",
    symbol: "FGBM",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K €",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10,
  },
  {
    name: "Euro-Schatz",
    symbol: "FGBS",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K €",
    months: "H,M,U,Z",
    tick: 0.005,
    value: 5,
  },
  {
    name: "Euro-Buxl",
    symbol: "FGBX",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K€",
    months: "H,M,U,Z",
    tick: 0.02,
    value: 20,
  },
  {
    name: "Euro-OAT",
    symbol: "FOAT",
    type: "Financials",
    exchange: "Eurex",
    unit: "EUR",
    contractSize: 100000,
    contractSizeExpl: "100K€",
    months: "H,M,U,Z",
    tick: 0.01,
    value: 10,
  },
]);
